---

- name: Ensure pgSSL image is pulled
  community.docker.docker_image:
    name: "{{ privacyint_pgssl_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ privacyint_pgssl_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else privacyint_pgssl_container_image_force_pull }}"

- name: Ensure pgSSL container network is created
  community.general.docker_network:
    name: "{{ privacyint_pgssl_container_network }}"
    driver: bridge

- name: Ensure pgSSL systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/pgssl.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ privacyint_pgssl_identifier }}.service"
    mode: 0640